/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateProject: typeof import('./src/components/CreateProject.vue')['default']
    DropFile: typeof import('./src/components/DropFile.vue')['default']
    EmployeeList: typeof import('./src/components/EmployeeList.vue')['default']
    EmployeesUpload: typeof import('./src/components/EmployeesUpload.vue')['default']
    IMaterialSymbolsAccountCircleOutline: typeof import('~icons/material-symbols/account-circle-outline')['default']
    IMaterialSymbolsCheckCircle: typeof import('~icons/material-symbols/check-circle')['default']
    IMaterialSymbolsContentCopyOutline: typeof import('~icons/material-symbols/content-copy-outline')['default']
    IMaterialSymbolsDoNotDisturbOnOutline: typeof import('~icons/material-symbols/do-not-disturb-on-outline')['default']
    IMaterialSymbolsGroupOutline: typeof import('~icons/material-symbols/group-outline')['default']
    IMaterialSymbolsMenuRounded: typeof import('~icons/material-symbols/menu-rounded')['default']
    IMaterialSymbolsSignalCellularAlt: typeof import('~icons/material-symbols/signal-cellular-alt')['default']
    IMdiApps: typeof import('~icons/mdi/apps')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IMdiChevronUpDown: typeof import('~icons/mdi/chevron-up-down')['default']
    IMdiFormatColumns: typeof import('~icons/mdi/format-columns')['default']
    IMdiLogout: typeof import('~icons/mdi/logout')['default']
    IMdiMoonWaxingCrescent: typeof import('~icons/mdi/moon-waxing-crescent')['default']
    IMdiRestoreClock: typeof import('~icons/mdi/restore-clock')['default']
    IMdiSlider: typeof import('~icons/mdi/slider')['default']
    IMdiWebCheck: typeof import('~icons/mdi/web-check')['default']
    IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    KliemtLogo: typeof import('./src/components/KliemtLogo.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    ModalDialog: typeof import('./src/components/ModalDialog.vue')['default']
    PieChart: typeof import('./src/components/PieChart.vue')['default']
    ProjectDashboard: typeof import('./src/components/ProjectDashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
