/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEmployeeForm: typeof import('./src/components/AddEmployeeForm.vue')['default']
    CreateProject: typeof import('./src/components/CreateProject.vue')['default']
    EmployeeList: typeof import('./src/components/EmployeeList.vue')['default']
    ExportPdfForm: typeof import('./src/components/ExportPdfForm.vue')['default']
    IMaterialSymbolsAccountCircleOutline: typeof import('~icons/material-symbols/account-circle-outline')['default']
    IMaterialSymbolsCheckCircle: typeof import('~icons/material-symbols/check-circle')['default']
    IMaterialSymbolsDeleteOutline: typeof import('~icons/material-symbols/delete-outline')['default']
    IMaterialSymbolsDoNotDisturbOnOutline: typeof import('~icons/material-symbols/do-not-disturb-on-outline')['default']
    IMaterialSymbolsDownload: typeof import('~icons/material-symbols/download')['default']
    IMaterialSymbolsMenuRounded: typeof import('~icons/material-symbols/menu-rounded')['default']
    IMaterialSymbolsTravelExploreRounded: typeof import('~icons/material-symbols/travel-explore-rounded')['default']
    IMdiApps: typeof import('~icons/mdi/apps')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IMdiChevronUpDown: typeof import('~icons/mdi/chevron-up-down')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiFormatColumns: typeof import('~icons/mdi/format-columns')['default']
    IMdiLogout: typeof import('~icons/mdi/logout')['default']
    IMdiMoonWaxingCrescent: typeof import('~icons/mdi/moon-waxing-crescent')['default']
    IMdiSlider: typeof import('~icons/mdi/slider')['default']
    IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    KliemtLogo: typeof import('./src/components/KliemtLogo.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    ModalDialog: typeof import('./src/components/ModalDialog.vue')['default']
    PieChart: typeof import('./src/components/PieChart.vue')['default']
    ProjectDashboard: typeof import('./src/components/ProjectDashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
